---
name: Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: nest-clean
        ports: [5432:5432]
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Configure database variables
        run: |
          echo "DATABASE_URL=postgres://postgres:docker@localhost:5432/nest-clean" >> $GITHUB_ENV
      - name: Wait for PostgreSQL setup
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in ${seq 1 10}; do 
            nc -z postgres 5432 && echo "PostgreSQL is ready! :)" && break
            echo "PostgreSQL is not ready yet, retrying in 5 seconds...($i/10)"
            sleep 5
          done
          nc -z postgres 5432 || (echo "PostgreSQL is still not ready after 10 attempts, exiting." && exit 1)
      - name: Run unit tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
